name: Chromatic Deployment

on:
  push:
    paths:
      - 'src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v20.14.0

      - name: Install dependencies
        run: yarn install

      - name: Build and Deploy to Chromatic for review-with-ai
        run: npx chromatic --project-token=${{secrets.CHROMATIC_TOKEN}} --exit-zero-on-changes
